function transactions = ConvertBinanceFeeOnly(binance)
%CONVERTBINANCEFEEONLY Summary of this function goes here

noneAsset = CreateCategoricalNone(height(binance));
nanValue = NaN(size(noneAsset));
zeroValue = zeros(size(noneAsset));

transactions = table( ...
    binance.UTC_Time, ...
    noneAsset, ...
    zeroValue, ...
    zeroValue, ...
    zeroValue, ...
    binance.Coin, ...
    binance.Change, ...
    nanValue, ...
    nanValue, ...
    noneAsset, ...
    zeroValue, ...
    zeroValue, ...
    zeroValue);

transactions = RenameTransactionColumns(transactions);

return
end

