function names = GetTransactionBlankColumnNames()
%GETTRANSACTIONBLANKCOLUMNNAMES Summary of this function goes here

names = { ...
    'Var1', ...
    'Var2', ...
    'Var3', ...
    'Var4', ...
    'Var5', ...
    'Var6', ...
    'Var7', ...
    'Var8', ...
    'Var9', ...
    'Var10', ...
    'Var11', ...
    'Var12', ...
    'Var13'};

return
end

