function names = GetTransactionColumnNames()
%GETTRANSACTIONCOLUMNNAMES Summary of this function goes here

names = { ...
    'Timestamp', ...
    'ToAsset', ...
    'ToQuantity', ...
    'ToRate', ...
    'ToTotal', ...
    'FeeAsset', ...
    'FeeQuantity', ...
    'FeeRate', ...
    'FeeTotal', ...
    'FromAsset', ...
    'FromQuantity', ...
    'FromRate', ...
    'FromTotal'};

return
end

