function transactions = ConvertNexoToOnly(nexo,gbpusd)
%CONVERTNEXOTOONLY Summary of this function goes here

noneAsset = CreateCategoricalNone(height(nexo));
zeroValue = zeros(size(noneAsset));

transactions = table( ...
    nexo.DateTime, ...
    nexo.Currency, ...
    str2double(nexo.Amount), ...
    (nexo.USDEquivalent./str2double(nexo.Amount))*gbpusd, ...
    nexo.USDEquivalent*gbpusd, ...
    noneAsset, ...
    zeroValue, ...
    zeroValue, ...
    zeroValue, ...
    noneAsset, ...
    zeroValue, ...
    zeroValue, ...
    zeroValue);

transactions = RenameTransactionColumns(transactions);

return
end

